// ============================================================
// HIEROGLYPH DATA
// Sources: Gardiner's Sign List, Unicode Egyptian Hieroglyphs block (U+13000–U+1342F)
// Transliteration uses standard Egyptological conventions
// ============================================================

const HIEROGLYPHS = {

  // ── UNILITERALS (the "alphabet" – one consonant per sign) ──────────────────
  uniliterals: [
    {
      id: 'G001',
      unicode: '𓄿',
      gardiner: 'G001',
      transliteration: 'ȝ',
      pronunciation: 'aleph – glottal stop (like the pause in "uh-oh")',
      name: 'Egyptian Vulture',
      category: 'uniliteral',
      description: 'The Egyptian vulture (Neophron percnopterus). This sign represents the glottal stop consonant ȝ (aleph), one of the weakest consonants in Egyptian.',
      mnemonic: 'The vulture opens its beak with a sudden stop of breath.',
      examples: ['𓄿𓈖𓏏 (ȝnt – shrine)', '𓄿𓊪𓏏 (ȝpt – Apis bull)'],
    },
    {
      id: 'M017',
      unicode: '𓇋',
      gardiner: 'M017',
      transliteration: 'i',
      pronunciation: 'i – like "ee" in "feet"',
      name: 'Reed',
      category: 'uniliteral',
      description: 'A single reed leaf. Represents the consonant i, used as both a consonant and a vowel marker in writing.',
      mnemonic: 'The reed sways like the "ee" sound it represents.',
      examples: ['𓇋𓏏𓆑 (itf – father)', '𓇋𓎛𓂋𓏏 (iḥrt – sky)'],
    },
    {
      id: 'M017a',
      unicode: '𓇌',
      gardiner: 'M017a',
      transliteration: 'y',
      pronunciation: 'y – like "y" in "yes"',
      name: 'Double Reed',
      category: 'uniliteral',
      description: 'Two reed leaves. Represents the consonant y. Often appears at the end of words to indicate a masculine noun.',
      mnemonic: 'Two reeds for the double sound "yy" or simply "y".',
      examples: ['𓇌𓂋𓏏 (yrt – eye)', '𓇌𓈖 (yn – then/so)'],
    },
    {
      id: 'D036',
      unicode: '𓂝',
      gardiner: 'D036',
      transliteration: 'ʿ',
      pronunciation: 'ayin – voiced pharyngeal fricative (back of throat)',
      name: 'Forearm',
      category: 'uniliteral',
      description: 'A human forearm and hand. Represents the consonant ʿ (ayin), a guttural sound from deep in the throat with no English equivalent.',
      mnemonic: 'Reach your arm back into your throat to make this sound.',
      examples: ['𓂝𓈖𓐍 (ʿnḫ – life)', '𓂝𓈖𓐍𓏏 (ʿnḫt – ankh symbol)'],
    },
    {
      id: 'G017',
      unicode: '𓅱',
      gardiner: 'G017',
      transliteration: 'w',
      pronunciation: 'w – like "w" in "well"',
      name: 'Quail Chick',
      category: 'uniliteral',
      description: 'A quail chick (Coturnix coturnix). Represents the consonant w. Also used as a vowel marker for the "oo" sound.',
      mnemonic: 'The chick wears a "w" shape in its feathers.',
      examples: ['𓅱𓊪𓅱𓂋𓏏 (wpwrt – Wepwawet)', '𓅱𓈖 (wn – to be/exist)'],
    },
    {
      id: 'D058',
      unicode: '𓃀',
      gardiner: 'D058',
      transliteration: 'b',
      pronunciation: 'b – like "b" in "bird"',
      name: 'Leg and Foot',
      category: 'uniliteral',
      description: 'A human leg and foot. Represents the consonant b.',
      mnemonic: 'Imagine kicking a ball – "b" for boot.',
      examples: ['𓃀𓈖𓏏 (bnt – harp)', '𓃀𓌀 (bi – soul/character)'],
    },
    {
      id: 'Q003',
      unicode: '𓊪',
      gardiner: 'Q003',
      transliteration: 'p',
      pronunciation: 'p – like "p" in "pyramid"',
      name: 'Stool / Reed Mat',
      category: 'uniliteral',
      description: 'A woven reed mat or low stool. Represents the consonant p.',
      mnemonic: 'A platform to sit on – "p" for platform.',
      examples: ['𓊪𓏏 (pt – sky/heaven)', '𓊪𓈖 (pn – this)'],
    },
    {
      id: 'I009',
      unicode: '𓆑',
      gardiner: 'I009',
      transliteration: 'f',
      pronunciation: 'f – like "f" in "pharaoh"',
      name: 'Horned Viper',
      category: 'uniliteral',
      description: 'The horned viper (Cerastes cornutus). Represents the consonant f.',
      mnemonic: 'The viper strikes fast – "f" for fangs.',
      examples: ['𓆑𓂧 (fd – four)', '𓆑𓈖𓂧𓅱 (fndw – nose)'],
    },
    {
      id: 'G017b',
      unicode: '𓅓',
      gardiner: 'G017b',
      transliteration: 'm',
      pronunciation: 'm – like "m" in "mummy"',
      name: 'Owl',
      category: 'uniliteral',
      description: 'A little owl (Athena noctua), shown in front view. Represents the consonant m.',
      mnemonic: 'The owl goes "m-m-m" while contemplating the night.',
      examples: ['𓅓𓂋𓏏 (mrt – beloved)', '𓅓𓈖 (mn – to remain/endure)'],
    },
    {
      id: 'N035',
      unicode: '𓈖',
      gardiner: 'N035',
      transliteration: 'n',
      pronunciation: 'n – like "n" in "Nile"',
      name: 'Water / Ripple',
      category: 'uniliteral',
      description: 'A wavy line representing water or a water ripple. Represents the consonant n. One of the most common hieroglyphs.',
      mnemonic: 'The waves of the Nile spell "n".',
      examples: ['𓈖𓏏𓂋 (ntr – god/divine)', '𓈖𓆑𓂋 (nfr – good/beautiful)'],
    },
    {
      id: 'D021',
      unicode: '𓂋',
      gardiner: 'D021',
      transliteration: 'r',
      pronunciation: 'r – like "r" in "Ra" (slightly rolled)',
      name: 'Mouth',
      category: 'uniliteral',
      description: 'A human mouth shown in profile. Represents the consonant r.',
      mnemonic: 'The mouth opens to say "r-r-r".',
      examples: ['𓂋𓏏 (rt – form/manner)', '𓂋𓈖 (rn – name)'],
    },
    {
      id: 'O004',
      unicode: '𓉔',
      gardiner: 'O004',
      transliteration: 'h',
      pronunciation: 'h – like "h" in "house" (aspirated)',
      name: 'Reed Shelter / Hut',
      category: 'uniliteral',
      description: 'A simple reed shelter or hut. Represents the consonant h, the softest of the four "h" sounds in Egyptian.',
      mnemonic: 'The shelter protects from the heat – "h" for hot.',
      examples: ['𓉔𓂋𓅱 (hrw – day/Horus)', '𓉔𓂝𓈖 (hʿn – to rejoice)'],
    },
    {
      id: 'V028',
      unicode: '𓎛',
      gardiner: 'V028',
      transliteration: 'ḥ',
      pronunciation: 'ḥ – like "h" but from lower in throat (emphatic)',
      name: 'Twisted Flax Wick',
      category: 'uniliteral',
      description: 'A twisted flax wick used in oil lamps. Represents ḥ, a slightly heavier "h" sound than plain h.',
      mnemonic: 'The wick burns with a harder breath – ḥ.',
      examples: ['𓎛𓂋𓅱 (ḥrw – face)', '𓎛𓊪𓅱 (ḥpw – Apis)'],
    },
    {
      id: 'Aa001',
      unicode: '𓐍',
      gardiner: 'Aa001',
      transliteration: 'ḫ',
      pronunciation: 'ḫ – like Scottish "loch" (velar fricative)',
      name: 'Placenta / Sieve',
      category: 'uniliteral',
      description: 'Possibly represents a placenta or a sieve. Represents ḫ, a rasping sound from the back of the mouth like the German "Bach" or Scottish "loch".',
      mnemonic: 'The roughest "h" – scrape the back of your throat.',
      examples: ['𓐍𓂋𓅱 (ḫrw – voice/word)', '𓐍𓈖𓅓 (ḫnm – Khnum god)'],
    },
    {
      id: 'F032',
      unicode: '𓄡',
      gardiner: 'F032',
      transliteration: 'ẖ',
      pronunciation: 'ẖ – a softer velar fricative, between h and ḫ',
      name: 'Animal Belly',
      category: 'uniliteral',
      description: 'The belly and tail of a mammal, seen from below. Represents ẖ, another variant of the "kh" range of sounds.',
      mnemonic: 'From the belly comes a deep, breathy sound.',
      examples: ['𓄡𓈖𓅱𓏏 (ẖnwt – inner chamber)', '𓄡𓂋 (ẖr – under/with)'],
    },
    {
      id: 'O034',
      unicode: '𓊃',
      gardiner: 'O034',
      transliteration: 'z',
      pronunciation: 'z – like "s" or "z" (varied by period)',
      name: 'Door Bolt',
      category: 'uniliteral',
      description: 'A door bolt or pin. Represents z (sometimes read as s in older texts). By the Middle Kingdom this merged with s.',
      mnemonic: 'The bolt slides with a "z" or "s" sound.',
      examples: ['𓊃𓅓𓅱 (zmw – papyrus)', '𓊃𓈖 (zn – to pass)'],
    },
    {
      id: 'S029',
      unicode: '𓋴',
      gardiner: 'S029',
      transliteration: 's',
      pronunciation: 's – like "s" in "sphinx"',
      name: 'Folded Cloth',
      category: 'uniliteral',
      description: 'A folded piece of cloth, possibly linen. Represents the consonant s.',
      mnemonic: 'The cloth folds smoothly – "s" for silk.',
      examples: ['𓋴𓈖 (sn – brother/to kiss)', '𓋴𓊪 (sp – time/occasion)'],
    },
    {
      id: 'N037',
      unicode: '𓈙',
      gardiner: 'N037',
      transliteration: 'š',
      pronunciation: 'š – like "sh" in "shadow"',
      name: 'Garden Pool',
      category: 'uniliteral',
      description: 'A rectangular pool or lake in a garden, shown from above. Represents the sound š (like English "sh").',
      mnemonic: 'The pool shimmers – "sh" for shimmer.',
      examples: ['𓈙𓂧𓅱 (šdw – pool/lake)', '𓈙𓂋𓅱 (šrw – boy/child)'],
    },
    {
      id: 'N029',
      unicode: '𓈎',
      gardiner: 'N029',
      transliteration: 'q',
      pronunciation: 'q – like "k" but from the very back of throat',
      name: 'Hill Slope',
      category: 'uniliteral',
      description: 'A sloping hill or dune. Represents q, a deep "k" sound (uvular stop) with no direct English equivalent.',
      mnemonic: 'Climb the hill to reach the back of the throat.',
      examples: ['𓈎𓂋𓏏 (qrt – cave)', '𓈎𓃀 (qb – coolness/to pour)'],
    },
    {
      id: 'V031',
      unicode: '𓎡',
      gardiner: 'V031',
      transliteration: 'k',
      pronunciation: 'k – like "k" in "king"',
      name: 'Basket with Handle',
      category: 'uniliteral',
      description: 'A wicker basket with a handle. Represents the consonant k.',
      mnemonic: 'The king carries a basket – "k" for king.',
      examples: ['𓎡𓈖 (kn – brave/strong)', '𓎡𓂧 (kd – to build/shape)'],
    },
    {
      id: 'W011',
      unicode: '𓎢',
      gardiner: 'W011',
      transliteration: 'g',
      pronunciation: 'g – like "g" in "god"',
      name: 'Jar Stand',
      category: 'uniliteral',
      description: 'A clay jar stand. Represents the consonant g.',
      mnemonic: 'The god rests the jar on a stand – "g" for god.',
      examples: ['𓎢𓃀𓅱 (gbw – earth/goose)', '𓎢𓈖 (gn – delicate/weak)'],
    },
    {
      id: 'X001',
      unicode: '𓏏',
      gardiner: 'X001',
      transliteration: 't',
      pronunciation: 't – like "t" in "tomb"',
      name: 'Bread Loaf',
      category: 'uniliteral',
      description: 'A round or cone-shaped bread loaf. Represents the consonant t. Also frequently serves as the feminine ending of nouns.',
      mnemonic: 'The loaf baked in the tomb – "t" for tomb.',
      examples: ['𓏏𓈖 (tn – you (masc.pl))', '𓏏𓂋 (tr – season/time)'],
    },
    {
      id: 'V013',
      unicode: '𓍿',
      gardiner: 'V013',
      transliteration: 'ṯ',
      pronunciation: 'ṯ – like "ch" in "cheese" or "tj"',
      name: 'Tethering Rope',
      category: 'uniliteral',
      description: 'A rope used for tethering animals. Represents ṯ, a sound like "tj" or "ch" – an affricate.',
      mnemonic: 'The rope ties with a "ch" snapping sound.',
      examples: ['𓍿𓈖𓅓𓏏 (ṯnmt – type of vessel)', '𓍿𓌀 (ṯz – to bind/knot)'],
    },
    {
      id: 'D046',
      unicode: '𓂧',
      gardiner: 'D046',
      transliteration: 'd',
      pronunciation: 'd – like "d" in "dead"',
      name: 'Hand',
      category: 'uniliteral',
      description: 'A human hand. Represents the consonant d.',
      mnemonic: 'The hand reaches down – "d" for down.',
      examples: ['𓂧𓂝𓏏 (dʿt – horizon?)', '𓂧𓂋𓅱 (drw – limit/end)'],
    },
    {
      id: 'I010',
      unicode: '𓆓',
      gardiner: 'I010',
      transliteration: 'ḏ',
      pronunciation: 'ḏ – like "j" in "judge" or "dj"',
      name: 'Cobra / Egyptian Asp',
      category: 'uniliteral',
      description: 'An Egyptian cobra rearing up. Represents ḏ, a sound like "dj" – a palatal affricate.',
      mnemonic: 'The cobra strikes like a sharp "dj" sound.',
      examples: ['𓆓𓂧𓏏 (ḏdt – Djedet/Mendes)', '𓆓𓂧 (ḏd – to say/speak)'],
    },
  ],

  // ── COMMON BILITERALS (two-consonant signs) ─────────────────────────────────
  biliterals: [
    {
      id: 'D028',
      unicode: '𓂀',
      gardiner: 'D028',
      transliteration: 'ir',
      pronunciation: 'ir – "eer"',
      name: 'Eye',
      category: 'biliteral',
      description: 'The human eye. Reads as ir or iir. Also used as a determinative for verbs of seeing and for the word "eye" (irt).',
      mnemonic: 'The eye sees – ir is to do/make in Egyptian.',
      examples: ['𓂀𓏏 (irt – eye / to do)', '𓂀𓈖 (irn – to observe)'],
    },
    {
      id: 'S034',
      unicode: '𓋹',
      gardiner: 'S034',
      transliteration: 'ʿnḫ',
      pronunciation: 'ankh – "ahnk"',
      name: 'Ankh',
      category: 'biliteral',
      description: 'The ankh, a looped cross. One of the most iconic Egyptian symbols, meaning "life." Used both as a word and as a triliteral sign.',
      mnemonic: 'The key of life – the ankh opens the door to living.',
      examples: ['𓋹 (ʿnḫ – life)', '𓋹𓌀𓅱𓈖𓋀 (ʿnḫ wḏȝ snb – "may he live, be prosperous and healthy")'],
    },
    {
      id: 'N016',
      unicode: '𓇾',
      gardiner: 'N016',
      transliteration: 'tȝ',
      pronunciation: 'ta – "tah"',
      name: 'Land / Earth',
      category: 'biliteral',
      description: 'A flat strip of land with grain/sand on top. Reads as tȝ meaning "land" or "earth." Common in geographic terms.',
      mnemonic: 'The flat land of Egypt stretches to the horizon.',
      examples: ['𓇾𓅱𓅓𓈖𓏏 (tȝ wmnt – Western Land)', '𓇾𓂋𓅓𓏏 (tȝ rmt – land of people)'],
    },
    {
      id: 'R008',
      unicode: '𓇯',
      gardiner: 'R008',
      transliteration: 'nṯr',
      pronunciation: 'netjer – "NET-cher"',
      name: 'God / Divine Flag',
      category: 'biliteral',
      description: 'A flag or standard on a pole, representing the divine. Reads as nṯr, meaning "god" or "divine." One of the most important words in Egyptian religion.',
      mnemonic: 'The divine flag waves above the temple – nṯr, god.',
      examples: ['𓇯 (nṯr – god)', '𓇯𓏏 (nṯrt – goddess)'],
    },
  ],

  // ── DETERMINATIVES (semantic classifiers, no phonetic value) ──────────────
  determinatives: [
    {
      id: 'A001-det',
      unicode: '𓀀',
      gardiner: 'A001',
      transliteration: '–',
      pronunciation: '(silent)',
      name: 'Seated Man',
      category: 'determinative',
      description: 'A seated man. Used as a determinative (classifier) after words relating to men, male persons, or masculine activities. Has no sound value of its own.',
      mnemonic: 'The man sits quietly at the end of "male" words.',
      examples: ['After words for "man", "scribe", "official"'],
    },
    {
      id: 'B001-det',
      unicode: '𓁐',
      gardiner: 'B001',
      transliteration: '–',
      pronunciation: '(silent)',
      name: 'Seated Woman',
      category: 'determinative',
      description: 'A seated woman. Used as a determinative after words relating to women or feminine roles.',
      mnemonic: 'The woman sits quietly at the end of "female" words.',
      examples: ['After words for "woman", "queen", "mother"'],
    },
    {
      id: 'N005-det',
      unicode: '𓇳',
      gardiner: 'N005',
      transliteration: '–',
      pronunciation: '(silent, or rʿ as a logogam)',
      name: 'Sun Disk',
      category: 'determinative',
      description: 'The sun disk. Used as a determinative after words relating to time, sun, light, and the god Ra. Also functions as a logogram for "Ra" or "day" (hrw).',
      mnemonic: 'The sun marks time – it ends words about the sky and time.',
      examples: ['After hrw (day), rʿ (Ra/sun)', '𓇳𓏤 (rʿ – sun/Ra)'],
    },
    {
      id: 'Z001-det',
      unicode: '𓏤',
      gardiner: 'Z001',
      transliteration: '–',
      pronunciation: '(silent)',
      name: 'Single Stroke',
      category: 'determinative',
      description: 'A single vertical stroke. Indicates that a preceding hieroglyph is being used as a logogram (word-sign) rather than a phonetic sign. Also marks the number 1.',
      mnemonic: 'One stroke means "read me literally as a word."',
      examples: ['𓇳𓏤 (rʿ – Ra)', '𓈖𓇌𓏤 (nwy – water/flood)'],
    },
  ],

  // ── COMMON WORDS / PHRASES ─────────────────────────────────────────────────
  vocabulary: [
    {
      id: 'w-ankh',
      hieroglyphs: '𓋹',
      transliteration: 'ʿnḫ',
      english: 'life',
      category: 'religion',
      notes: 'One of the most important Egyptian concepts and symbols. The ankh was carried by gods and given to pharaohs to sustain them.',
    },
    {
      id: 'w-nfr',
      hieroglyphs: '𓈖𓆑𓂋',
      transliteration: 'nfr',
      english: 'good / beautiful / perfect',
      category: 'adjective',
      notes: 'Extremely common word. Also used in names like Nefertiti ("the beautiful one has come") and Nefertari.',
    },
    {
      id: 'w-ra',
      hieroglyphs: '𓇳𓏤',
      transliteration: 'Rʿ',
      english: 'Ra (sun god)',
      category: 'religion',
      notes: 'The sun god, chief deity of the Egyptian pantheon. The sun disk hieroglyph is used as a logogram.',
    },
    {
      id: 'w-pr',
      hieroglyphs: '𓉐𓏤',
      transliteration: 'pr',
      english: 'house',
      category: 'noun',
      notes: 'The word for "house" or "estate." Appears in Per-Aa (Pharaoh), literally "Great House."',
    },
    {
      id: 'w-maat',
      hieroglyphs: '𓆄𓏏𓁦',
      transliteration: 'Mȝʿt',
      english: 'Maat (truth, justice, order)',
      category: 'religion',
      notes: 'The concept of cosmic order, truth, and justice. Personified as a goddess with a feather on her head.',
    },
    {
      id: 'w-sn',
      hieroglyphs: '𓋴𓈖',
      transliteration: 'sn',
      english: 'brother / to kiss',
      category: 'noun',
      notes: 'The same word means both "brother" and "to kiss" in Egyptian – determined by context and determinatives.',
    },
    {
      id: 'w-hrw',
      hieroglyphs: '𓇯𓂋𓅱',
      transliteration: 'Ḥrw',
      english: 'Horus',
      category: 'religion',
      notes: 'The falcon god Horus, son of Osiris and Isis. The living pharaoh was considered an incarnation of Horus.',
    },
    {
      id: 'w-wsir',
      hieroglyphs: '𓁹𓊨',
      transliteration: 'Wsir',
      english: 'Osiris',
      category: 'religion',
      notes: 'God of the afterlife and resurrection. The deceased pharaoh was identified with Osiris.',
    },
    {
      id: 'w-kmt',
      hieroglyphs: '𓆎𓅓𓏏𓆖',
      transliteration: 'Kmt',
      english: 'Kemet (Egypt – "the Black Land")',
      category: 'geography',
      notes: 'The ancient Egyptian name for Egypt, referring to the dark fertile soil of the Nile Valley, as opposed to Deshret ("the Red Land") – the desert.',
    },
    {
      id: 'w-nb',
      hieroglyphs: '𓎟',
      transliteration: 'nb',
      english: 'lord / all / every',
      category: 'noun',
      notes: 'Extremely versatile word. "Nb" can mean "lord," "master," or (with different spelling) "all/every." Common in royal titles.',
    },
    {
      id: 'w-ddt',
      hieroglyphs: '𓆓𓂧',
      transliteration: 'ḏd',
      english: 'to say / to speak',
      category: 'verb',
      notes: 'The word for speaking or saying. Used in the formula "ḏd mdw" (words to be spoken) in temple texts.',
    },
    {
      id: 'w-mry',
      hieroglyphs: '𓅓𓂋𓇌',
      transliteration: 'mry',
      english: 'beloved',
      category: 'adjective',
      notes: 'Common in royal epithets, e.g., "beloved of Amun." Forms part of many royal names.',
    },
  ],
};

// ── LESSONS DATA ───────────────────────────────────────────────────────────────
const LESSONS = [
  {
    id: 'intro',
    title: 'Introduction to Hieroglyphs',
    subtitle: 'What are Egyptian hieroglyphs?',
    icon: '𓂀',
    difficulty: 'beginner',
    duration: '10 min',
    content: [
      {
        type: 'text',
        body: `Egyptian hieroglyphs are one of the world's oldest writing systems, used for over 3,500 years (c. 3200 BCE – 400 CE). The word "hieroglyph" comes from Greek: hieros (sacred) + glyphe (carving), meaning "sacred carved [writings]."`,
      },
      {
        type: 'highlight',
        body: `The Egyptians called their script "the words of god" (𓇯𓏏𓂋𓅱 mdw nṯr – medu netjer), because they believed writing was a gift from the god Thoth.`,
      },
      {
        type: 'text',
        body: `Hieroglyphs can be read left-to-right, right-to-left, or top-to-bottom. The direction depends on which way the animal and human figures face – they always face the beginning of the text. Look for the animal faces to know where to start reading!`,
      },
      {
        type: 'subheading',
        body: 'Three types of hieroglyphic signs',
      },
      {
        type: 'list',
        items: [
          '<strong>Phonograms</strong> — Signs that represent sounds (consonants). Like letters in our alphabet. Examples: the mouth 𓂋 = "r", the water 𓈖 = "n".',
          '<strong>Logograms</strong> — Signs that represent a whole word directly. The sun disk 𓇳 = "Ra" or "sun." Often marked with a vertical stroke 𓏤.',
          '<strong>Determinatives</strong> — Silent signs added at the end of a word to show its category. The seated man 𓀀 tells you the word refers to a male person. They have no sound value.',
        ],
      },
      {
        type: 'text',
        body: `Egyptian hieroglyphs only write consonants — there are no vowels written (similar to Arabic and Hebrew). When we reconstruct ancient words, Egyptologists add "e" between consonants as a convention (e.g., "nfr" is pronounced something like "nefer").`,
      },
      {
        type: 'highlight',
        body: `The Rosetta Stone (196 BCE), discovered in 1799, was the key to decipherment. It contains the same text in hieroglyphs, Demotic script, and ancient Greek. Jean-François Champollion cracked the code in 1822.`,
      },
    ],
  },
  {
    id: 'alphabet',
    title: 'The Hieroglyphic Alphabet',
    subtitle: 'The 24 uniliteral signs',
    icon: '𓄿',
    difficulty: 'beginner',
    duration: '20 min',
    content: [
      {
        type: 'text',
        body: `Egyptian has a set of 24 "uniliteral" signs — each represents a single consonant sound. Together, they form what is often called the "hieroglyphic alphabet." Mastering these is your first major milestone.`,
      },
      {
        type: 'highlight',
        body: `Unlike our alphabet, these signs were never used alone as a complete writing system. Egyptians mixed them with multi-consonant signs and logograms. But learning the uniliterals is essential for reading any hieroglyphic text.`,
      },
      {
        type: 'subheading',
        body: 'Four "H" sounds',
      },
      {
        type: 'text',
        body: `Egyptian has four distinct H-like consonants — a feature completely foreign to English speakers:<br>
        <br>• <strong>h</strong> 𓉔 — like English "h" (soft, aspirated)<br>
        • <strong>ḥ</strong> 𓎛 — like "h" but with a slight rasp<br>
        • <strong>ḫ</strong> 𓐍 — like Scottish "loch" (velar fricative)<br>
        • <strong>ẖ</strong> 𓄡 — a softer version of ḫ`,
      },
      {
        type: 'subheading',
        body: 'Weak consonants and vowels',
      },
      {
        type: 'text',
        body: `Three signs (ȝ, i, w) are "weak" consonants that also serve as vowel markers. They are the building blocks of Egyptian morphology and appear constantly in verb forms and suffixes.`,
      },
      {
        type: 'subheading',
        body: 'Transliteration conventions',
      },
      {
        type: 'text',
        body: `Egyptologists use a special system to write Egyptian in Latin script. Key symbols to know:<br>
        <br>• <strong>ȝ</strong> (aleph) — glottal stop<br>
        • <strong>ʿ</strong> (ayin) — pharyngeal sound<br>
        • <strong>š</strong> — "sh" sound<br>
        • <strong>ḏ</strong> — "dj" sound<br>
        • <strong>ṯ</strong> — "tj" or "ch" sound`,
      },
    ],
  },
  {
    id: 'determinatives',
    title: 'Determinatives',
    subtitle: 'Silent signs that classify meaning',
    icon: '𓀀',
    difficulty: 'beginner',
    duration: '15 min',
    content: [
      {
        type: 'text',
        body: `Determinatives (also called semagrams or ideographic complements) are silent hieroglyphs placed at the end of a word to indicate its general meaning or category. They do not add any sound — they classify.`,
      },
      {
        type: 'highlight',
        body: `Think of determinatives as "hashtags" for ancient Egyptian words. They group words by concept and help readers distinguish between words that are spelled the same way but have different meanings.`,
      },
      {
        type: 'subheading',
        body: 'Common determinative categories',
      },
      {
        type: 'list',
        items: [
          '<strong>𓀀 Seated man</strong> — words relating to men, male roles (scribe, official, person)',
          '<strong>𓁐 Seated woman</strong> — words relating to women, female roles (mother, queen)',
          '<strong>𓇳 Sun disk</strong> — words relating to time, sun, light, and Ra',
          '<strong>𓆖 Roll of papyrus</strong> — abstract concepts, verbs, words for writing',
          '<strong>𓂻 Walking legs</strong> — words for movement, travel, actions',
          '<strong>𓂝 Raised arm</strong> — words for force, effort, high things',
          '<strong>𓏏 Bread loaf</strong> — (also phonetic t) marks feminine nouns',
          '<strong>𓌀 Crossed planks</strong> — words for god/divine (in some texts)',
        ],
      },
      {
        type: 'text',
        body: `Example: The word sn (𓋴𓈖) means both "brother" and "to kiss." With the determinative for "man" 𓀀 it means "brother." With the mouth determinative it means "to kiss." Same phonetic spelling — different determinative — different meaning!`,
      },
    ],
  },
  {
    id: 'reading',
    title: 'How to Read Hieroglyphs',
    subtitle: 'Direction, grouping, and order',
    icon: '𓂋',
    difficulty: 'intermediate',
    duration: '20 min',
    content: [
      {
        type: 'text',
        body: `Reading hieroglyphs requires learning to identify the direction of text and the logical grouping of signs. Unlike modern scripts with fixed direction, hieroglyphs adapt to aesthetic and architectural context.`,
      },
      {
        type: 'subheading',
        body: 'Reading direction',
      },
      {
        type: 'text',
        body: `Always find the human and animal figures first. They face the START of the text — read toward their faces.<br><br>
        • <strong>Figures face right</strong> → read right to left (most common in religious texts)<br>
        • <strong>Figures face left</strong> → read left to right<br>
        • <strong>Top to bottom</strong> → read column by column, then right to left or left to right`,
      },
      {
        type: 'subheading',
        body: 'Aesthetic grouping',
      },
      {
        type: 'text',
        body: `Egyptians arranged signs into compact, balanced groups to fill rectangular spaces. A tall sign might be combined with two shorter signs stacked on top of each other. This is purely for visual balance — the reading order is still determined by sign sequence, not position.`,
      },
      {
        type: 'highlight',
        body: `Royal names were enclosed in a cartouche (𓍹𓍺) — an oval loop with a horizontal bar. If you see a cartouche, you're reading a royal name! This was the key clue Champollion used in deciphering hieroglyphs from the Rosetta Stone.`,
      },
      {
        type: 'subheading',
        body: 'Honorific transposition',
      },
      {
        type: 'text',
        body: `In religious texts, divine or royal names are often written first out of respect, even if they come later in speech. For example, in "the house of Ra," Ra (𓇳) may appear before "house" (𓉐) even though grammatically house comes first. This is called "honorific transposition."`,
      },
    ],
  },
  {
    id: 'names',
    title: 'Royal Names & Cartouches',
    subtitle: 'Reading pharaoh names in hieroglyphs',
    icon: '𓍹',
    difficulty: 'intermediate',
    duration: '15 min',
    content: [
      {
        type: 'text',
        body: `One of the most exciting applications of hieroglyph knowledge is reading the names of famous pharaohs directly from monuments and artifacts. Royal names were enclosed in cartouches to protect them magically.`,
      },
      {
        type: 'highlight',
        body: `The word "cartouche" comes from French soldiers who thought the oval shape resembled a gun cartridge. Egyptians called it a shenu (𓌀), from the word "to encircle," symbolizing the king's rule over all that the sun encircles.`,
      },
      {
        type: 'subheading',
        body: 'Famous royal names',
      },
      {
        type: 'list',
        items: [
          '<strong>𓇳𓇋𓇌𓃀𓂋𓅱</strong> — Ramesses: Rʿ-ms-sw ("Ra has fashioned him")',
          '<strong>𓇳𓂝𓈖𓐍𓊪𓂋𓂋𓂋</strong> — Tutankhamun: Twt-ʿnḫ-Ȝmn ("Living image of Amun")',
          '<strong>𓎛𓆑𓂋𓏏𓆓𓅱</strong> — Nefertiti: Nfr-t-iti ("The beautiful one has come")',
          '<strong>𓄿𓃀𓂋𓅱𓎢𓂝𓂋𓏏</strong> — Cleopatra: Qlwpdrt (Greek name in Egyptian)',
        ],
      },
      {
        type: 'text',
        body: `When Champollion compared the Rosetta Stone cartouches, he recognized "Ptolemy" and "Cleopatra" and identified shared letters. This allowed him to decode the phonetic values of the signs and crack the entire system in 1822.`,
      },
    ],
  },
];
